In [ ]:
#data processing first step

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Reading the dataset
# Assuming the dataset is stored in a CSV file named 'molecules_data.csv'
data = pd.read_csv('nk1 data.csv')

# Displaying the first few rows of the dataset
print("Initial Dataset:")
print(data.head())

# Handling missing values - checking for any missing values in the dataset
missing_values = data.isnull().sum()
print("\nMissing Values:")
print(missing_values)

# Handling Categorical Data - Encoding 'mol_id' using Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['mol_id_encoded'] = le.fit_transform(data['MOLECULE'])

# Feature Scaling - Scaling numerical columns (e.g., A, B, C)
scaler = StandardScaler()
columns_to_scale = ['D']


# Splitting the data into training and testing sets
# Assuming 'gap' column as the target variable to predict
X = data.drop(['MOLECULE'], axis=1)  # Features
y = data['Act']  # Target variable

# Splitting the data into 80% training and 20% testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Displaying the preprocessed data
print("\nPreprocessed Dataset:")
print(X_train.head())
print(X_test.head())
print(y_train.head())
print(y_test.head())

Initial Dataset:
  MOLECULE     Act  D_2  D_3  D_4  D_36  D_37  D_38  D_39  D_40  ...  D_10963  \
0     M_18  6.1356    0    0    0     0     0     0     0     0  ...        0
1    M_225  6.8227    0    0    0     0     0     0     0     0  ...        0
2    M_369  6.5075    0    0    0     0     0     0     0     0  ...        0
3    M_372  6.7200    0    0    0     0     0     0     0     0  ...        0
4    M_408  6.4803    0    0    0     0     0     0     0     0  ...        0

   D_10970  D_10996  D_10998  D_11001  D_11028  D_11032  D_11039  D_11048  \
0        0        0        0        0        0        0        0        0
1        0        0        0        0        0        0        0        0
2        0        0        0        0        0        0        0        0
3        0        0        0        0        0        0        0        0
4        0        0        0        0        0        0        0        0

   D_11053
0        0
1        0
2        0
3        0
4        0

[5 rows x 5594 columns]

Missing Values:
MOLECULE    0
Act         0
D_2         0
D_3         0
D_4         0
           ..
D_11028     0
D_11032     0
D_11039     0
D_11048     0
D_11053     0
Length: 5594, dtype: int64

Preprocessed Dataset:
         Act  D_2  D_3  D_4  D_36  D_37  D_38  D_39  D_40  D_41  ...  D_10970  \
8142  8.0395    0    0    0     0     0     0     0     0     0  ...        0
2375  6.3968    0    0    0     0     0     0     0     0     0  ...        0
6795  7.8225    0    0    0     0     0     0     0     0     0  ...        0
4439  8.2277    0    0    0     0     0     0     0     0     0  ...        0
6195  8.2426    0    0    0     0     0     0     0     0     0  ...        0

      D_10996  D_10998  D_11001  D_11028  D_11032  D_11039  D_11048  D_11053  \
8142        0        0        0        0        0        0        0        0
2375        0        0        0        0        0        0        0        0
6795        0        0        0        0        0        0        0        0
4439        0        0        0        0        0        0        0        0
6195        0        0        0        0        0        0        0        0

      mol_id_encoded
8142            7428
2375            1529
6795            6081
4439            3690
6195            5481

[5 rows x 5594 columns]
         Act  D_2  D_3  D_4  D_36  D_37  D_38  D_39  D_40  D_41  ...  D_10970  \
5229  9.2994    0    0    0     0     0     0     0     0     0  ...        0
9868  9.5917    0    0    0     0     0     0     0     0     0  ...        0
6176  8.6182    0    0    0     0     0     0     0     0     0  ...        0
9495  9.5359    0    0    0     0     0     0     0     0     0  ...        0
1208  7.2744    0    0    0     0     0     0     0     0     0  ...        0

      D_10996  D_10998  D_11001  D_11028  D_11032  D_11039  D_11048  D_11053  \
5229        0        0        0        0        0        0        0        0
9868        0        0        0        0        0        0        0        0
6176        0        0        0        0        0        0        0        0
9495        0        0        0        0        0        0        0        0
1208        0        0        0        0        0        0        0        0

      mol_id_encoded
5229            4481
9868            9154
6176            5462
9495            8781
1208             344

[5 rows x 5594 columns]
8142    8.0395
2375    6.3968
6795    7.8225
4439    8.2277
6195    8.2426
Name: Act, dtype: float64
5229    9.2994
9868    9.5917
6176    8.6182
9495    9.5359
1208    7.2744
Name: Act, dtype: float64

In [ ]:
import pandas as pd

# Load your dataset from a CSV file
file_path = 'nk1 data.csv'  # Replace 'your_dataset.csv' with the path to your CSV file
df = pd.read_csv(file_path)

# Remove columns with all zero values
df = df.loc[:, (df != 0).any(axis=0)]

# Display the modified DataFrame
print(df)

print(df.head())

     MOLECULE     Act  D_2  D_3  D_4  D_36  D_37  D_38  D_39  D_40  ...  \
0        M_18  6.1356    0    0    0     0     0     0     0     0  ...
1       M_225  6.8227    0    0    0     0     0     0     0     0  ...
2       M_369  6.5075    0    0    0     0     0     0     0     0  ...
3       M_372  6.7200    0    0    0     0     0     0     0     0  ...
4       M_408  6.4803    0    0    0     0     0     0     0     0  ...
...       ...     ...  ...  ...  ...   ...   ...   ...   ...   ...  ...
9960  M_35008  9.6181    0    0    0     0     0     0     0     0  ...
9961  M_35009  7.8525    0    0    0     0     0     0     0     0  ...
9962  M_35010  8.4800    0    0    0     0     0     0     0     0  ...
9963  M_35011  8.8523    0    0    0     0     0     0     0     0  ...
9964  M_35012  9.4243    0    0    0     0     0     0     0     0  ...

      D_10963  D_10970  D_10996  D_10998  D_11001  D_11028  D_11032  D_11039  \
0           0        0        0        0        0        0        0        0
1           0        0        0        0        0        0        0        0
2           0        0        0        0        0        0        0        0
3           0        0        0        0        0        0        0        0
4           0        0        0        0        0        0        0        0
...       ...      ...      ...      ...      ...      ...      ...      ...
9960        0        0        0        0        0        0        0        0
9961        0        0        0        0        0        0        0        0
9962        0        0        0        0        0        0        0        0
9963        0        0        0        0        0        0        0        0
9964        0        0        0        0        0        0        0        0

      D_11048  D_11053
0           0        0
1           0        0
2           0        0
3           0        0
4           0        0
...       ...      ...
9960        0        0
9961        0        0
9962        0        0
9963        0        0
9964        0        0

[9965 rows x 5594 columns]
  MOLECULE     Act  D_2  D_3  D_4  D_36  D_37  D_38  D_39  D_40  ...  D_10963  \
0     M_18  6.1356    0    0    0     0     0     0     0     0  ...        0
1    M_225  6.8227    0    0    0     0     0     0     0     0  ...        0
2    M_369  6.5075    0    0    0     0     0     0     0     0  ...        0
3    M_372  6.7200    0    0    0     0     0     0     0     0  ...        0
4    M_408  6.4803    0    0    0     0     0     0     0     0  ...        0

   D_10970  D_10996  D_10998  D_11001  D_11028  D_11032  D_11039  D_11048  \
0        0        0        0        0        0        0        0        0
1        0        0        0        0        0        0        0        0
2        0        0        0        0        0        0        0        0
3        0        0        0        0        0        0        0        0
4        0        0        0        0        0        0        0        0

   D_11053
0        0
1        0
2        0
3        0
4        0

[5 rows x 5594 columns]